### ISSUE TITLE
program gets stuck loading the trained model

### ISSUE THREAD

**Issue by lqsdust** [sebasutp/trajectory_forcasting#2]
![traceback info](https://user-images.githubusercontent.com/6175772/158939013-afbda5d7-e589-440b-9288-a98172a5f50e.JPG)
  Hi, I've encountered some problem in running  plot_dist.py in the examples folder. The code ran smooth all through the training phase, I've got the trained model under sim_model directory. However, problem occured when I tried to run plot_dist.py, the program just got stuck and no reponse. It seems that the problem stems from the "pred = traj.load_model(args.model)" in the plot_dist.py, which calls several load_model functions in keras, as in: decoder = keras.models.load_model( os.path.join(path,'decoder.h5')). from dcgm.py. 
     The environment I am using to run this code is as follows: python 3.9.7, tensorflow 2.4.1, keras 2.4.3 in ubuntu 18.04.6 LTS. Everytime the program gets stuck, I have to use ctrl+c to interrupt the process, below are the traceback information prompted when the process was interrupted. Any advice for solving this issue? Thanks~

**Comment by lqsdust** [comment]
Hi,guys~ The problem was solved thanks to kind help from Dr.Sebastian @sebasutp.  It turns out that the code on this repo was designed to work with TF 1.0 and Keras. Therefore some modifications should be done to be able to run it with TF 2.0 and tf.Keras. The most important modification is to deactivate eager mode in dcgm.py . Hope you guys find this helpful when running the code with TF2.0~

**Comment by Roy-fyq** [comment]
Hello, I'm trying to run train_dcgm.py recently, but i met some problems in TF version. I have tried TF1.4.1 and TF 2.16.1, they don't work. Can you share your TF version if possible. Thank you!

**Comment by Roy-fyq** [comment]
> Hello, I'm trying to run train_dcgm.py recently, but i met some problems in TF version. I have tried TF1.4.1 and TF 2.16.1, they don't work. Can you share your TF version if possible. Thank you!

I got it
