### ISSUE TITLE
TF Version

### ISSUE THREAD

**Issue by Roy-fyq** [sebasutp/trajectory_forcasting#3]
I have tried TF1.4.1 and TF 2.16.1, but met a lot of problems. Could you provide the version you used in this repo if possible. Thank you!
@sebasutp

**Comment by Roy-fyq** [comment]
I got it!

**Comment by sebasutp** [comment]
Hi. I did this a long time ago and TF has changed a lot since. I am glad to see you solved it. If you can share what you did here I am sure it can help others. Back in the day, the instructions I wrote in the readme were good enough :)
